package com.pranav.normcore.Activities;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.pranav.normcore.CustomClasses.Influncer;
import com.pranav.normcore.R;

public class InfluncerSignup extends AppCompatActivity {

    private static final String TAG = "TAKATAK";
    EditText editTextName, editTextUsername, editTextInstagramUsername, editTextContact, editTextEmail, editTextPassword;
    Button buttonSignUp;
    ProgressBar progressBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_influncer_signup);

        editTextName = findViewById(R.id.editTextName);
        editTextUsername = findViewById(R.id.editTextUsername);
        editTextInstagramUsername = findViewById(R.id.editTextInstagramUsername);
        editTextContact = findViewById(R.id.editTextContact);
        editTextEmail = findViewById(R.id.editTextEmail);
        editTextPassword = findViewById(R.id.editTextPassword);
        buttonSignUp = findViewById(R.id.buttonRegister);
        progressBar = findViewById(R.id.progressBar);

        buttonSignUp.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                progressBar.setVisibility(View.VISIBLE);

                createInfluencer();
            }
        });
    }

    void createInfluencer() {
        final String name = editTextName.getText().toString().trim();
        final String username = editTextUsername.getText().toString().trim();
        final String email = editTextEmail.getText().toString().trim();
        final String contact = editTextContact.getText().toString().trim();
        final String instagramUsername = editTextInstagramUsername.getText().toString().trim();
        String password = editTextPassword.getText().toString().trim();

        final FirebaseAuth mAuth = FirebaseAuth.getInstance();

        mAuth.createUserWithEmailAndPassword(email, password)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            // Sign in success, update UI with the signed-in user's information
                            Log.d(TAG, "createUserWithEmail:success");
                            FirebaseUser user = mAuth.getCurrentUser();
                            if (user != null) {
                                String userId = user.getUid();
                                createUserInDatabase(name,username,email,contact,instagramUsername,userId);
                            }
                            updateUI(user);
                        } else {
                            // If sign in fails, display a message to the user.
                            Log.w(TAG, "createUserWithEmail:failure", task.getException());
                            Toast.makeText(InfluncerSignup.this, "Authentication failed.",
                                    Toast.LENGTH_SHORT).show();
                            updateUI(null);
                        }

                        // ...
                    }
                });
    }


    void createUserInDatabase(String name, String username, String email, String contact, String instagramUsername,String uid){
        // Creates a user object to prepare to store the users data
        Influncer influncer = new Influncer(name, username, email,contact,instagramUsername);

        /*
         *  This stores the users data in the 'users' reference in the database using the
         *  user's unique id generated by firebase
         */
        FirebaseDatabase.getInstance()
                .getReference("Influencer")
                .child(uid)
                .setValue(influncer, new DatabaseReference.CompletionListener() {
                    @Override
                    public void onComplete(@Nullable DatabaseError databaseError, @NonNull DatabaseReference databaseReference) {
                        if(databaseError == null){
                            /*
                             *  This method is called when the users information is successfully saved into
                             *  the firebase
                             */
                            progressBar.setVisibility(View.GONE);

                            // The finish method destroys the activity and preparing to leave the activity to
                            // the Home page
                            onBackPressed();

                            // Intent is created in order to leave this activity to the Home page
                            //Intent in = new Intent(getApplicationContext(), Home.class);

                        }
                        else {
                            // This displays a toast message to the user when the user is not able to signup
                            Toast.makeText(InfluncerSignup.this, "Couldn't register, try again",
                                    Toast.LENGTH_SHORT).show();
                            progressBar.setVisibility(View.GONE);
                        }
                    }
                });
    }

    private void updateUI(FirebaseUser user) {

    }
}